
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID IDL LINHA_B VALORdic : EsEs : E LINHA_B EsEs : EE : ItensItens : Item '#' ItensItens : ItemItem : AtrCItem : LingAtrC : ID ':' VALORLing : IDL ':' TsTs : Ts TTs : TT : '-' VALOR AtrTsAtrTs : AtrTs2AtrTs : AtrTs2 : AtrTs2 AtrTAtrTs2 : AtrTAtrT : '+' ID ':' VALOR"
    
_lr_action_items = {'ID':([0,10,11,25,],[8,8,8,27,]),'IDL':([0,10,11,],[9,9,9,]),'$end':([1,2,3,4,5,6,7,14,15,16,17,18,20,21,22,23,24,26,29,],[0,-1,-3,-4,-6,-7,-8,-2,-5,-9,-10,-12,-11,-15,-13,-14,-17,-16,-18,]),'LINHA_B':([3,4,5,6,7,15,16,17,18,20,21,22,23,24,26,29,],[10,-4,-6,-7,-8,-5,-9,-10,-12,-11,-15,-13,-14,-17,-16,-18,]),'#':([5,6,7,16,17,18,20,21,22,23,24,26,29,],[11,-7,-8,-9,-10,-12,-11,-15,-13,-14,-17,-16,-18,]),':':([8,9,27,],[12,13,28,]),'VALOR':([12,19,28,],[16,21,29,]),'-':([13,17,18,20,21,22,23,24,26,29,],[19,19,-12,-11,-15,-13,-14,-17,-16,-18,]),'+':([21,23,24,26,29,],[25,25,-17,-16,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dic':([0,],[1,]),'Es':([0,10,],[2,14,]),'E':([0,10,],[3,3,]),'Itens':([0,10,11,],[4,4,15,]),'Item':([0,10,11,],[5,5,5,]),'AtrC':([0,10,11,],[6,6,6,]),'Ling':([0,10,11,],[7,7,7,]),'Ts':([13,],[17,]),'T':([13,17,],[18,20,]),'AtrTs':([21,],[22,]),'AtrTs2':([21,],[23,]),'AtrT':([21,23,],[24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dic","S'",1,None,None,None),
  ('dic -> Es','dic',1,'p_1','yacc.py',5),
  ('Es -> E LINHA_B Es','Es',3,'p_2','yacc.py',9),
  ('Es -> E','Es',1,'p_3','yacc.py',13),
  ('E -> Itens','E',1,'p_4','yacc.py',17),
  ('Itens -> Item # Itens','Itens',3,'p_5','yacc.py',21),
  ('Itens -> Item','Itens',1,'p_6','yacc.py',25),
  ('Item -> AtrC','Item',1,'p_7','yacc.py',29),
  ('Item -> Ling','Item',1,'p_8','yacc.py',33),
  ('AtrC -> ID : VALOR','AtrC',3,'p_9','yacc.py',37),
  ('Ling -> IDL : Ts','Ling',3,'p_10','yacc.py',41),
  ('Ts -> Ts T','Ts',2,'p_11','yacc.py',45),
  ('Ts -> T','Ts',1,'p_12','yacc.py',49),
  ('T -> - VALOR AtrTs','T',3,'p_13','yacc.py',53),
  ('AtrTs -> AtrTs2','AtrTs',1,'p_14','yacc.py',57),
  ('AtrTs -> <empty>','AtrTs',0,'p_15','yacc.py',61),
  ('AtrTs2 -> AtrTs2 AtrT','AtrTs2',2,'p_16','yacc.py',65),
  ('AtrTs2 -> AtrT','AtrTs2',1,'p_17','yacc.py',69),
  ('AtrT -> + ID : VALOR','AtrT',4,'p_19','yacc.py',73),
]
